---
kind: pipeline
name: node22
# clone:
#   disable: false
steps:
  - name: test
    image: node:22.13.0-alpine3.21
    commands:
      - npm install
      - npm test

---
kind: pipeline
name: node20
# clone:
#   disable: false
steps:
  - name: test
    image: node:20.18.1-alpine3.21
    commands:
      - npm install
      - npm test
